[workspace]
members = [
    "chess",
    "even_block_hash",
]

resolver = "2"

[workspace.dependencies]
extism-pdk = "1.0.1"

# Tell `rustc` to optimize for small code size.
[profile.release]
opt-level = "z"
lto = true
