[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
extism-pdk = { workspace = true }
anyhow = "1.0"
pleco = "0.5.0"
serde = "1.0"
serde_json = "1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
