[package]
name = "even_block_hash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
extism-pdk = { workspace = true }
hex = "0.4.3"

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
